flow_url = "https://prod-89.westeurope.logic.azure.com:443/workflows/f214ff053f1b4e62838db5d3c50fc08e/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=EhW-8xLMR7suaKXbMIk9iW73cJ_fgDHhwm2qXJcogu0"
launch_key = "Terminator_2025"

